try {
    throw Error('hola again')
} catch {
    error
}